// Curated subset of popular Google Fonts (extend as desired)
export const GOOGLE_FONTS: string[] = [
    'Inter',
    'Roboto',
    'Open Sans',
    'Lato',
    'Montserrat',
    'Poppins',
    'Source Sans Pro',
    'Nunito',
    'Raleway',
    'Ubuntu',
    'Merriweather',
    'Oswald',
    'Playfair Display',
    'Work Sans',
    'Fira Sans',
    'Rubik',
    'Quicksand',
    'Inconsolata',
    'PT Sans',
    'PT Serif',
    'Noto Sans',
    'Noto Serif',
    'Titillium Web',
    'Heebo',
    'Karla',
    'Barlow',
    'Cabin',
    'DM Sans',
    'Manrope',
    'Space Grotesk',
    'Space Mono',
    'Bebas Neue',
    'Archivo',
    'Arimo',
    'Asap',
    'Assistant',
    'Bitter',
    'Cairo',
    'DM Mono',
    'Exo 2',
    'Hind',
    'IBM Plex Sans',
    'IBM Plex Mono',
    'IBM Plex Serif',
    'Josefin Sans',
    'Kanit',
    'Libre Baskerville',
    'Maven Pro',
    'Mulish',
    'Overpass',
    'Prompt',
    'Signika',
    'Teko',
    'Urbanist',
];
